### ISSUE TITLE
minor mistake in page 89

### ISSUE THREAD

**Issue by AaronSmart** [daijiale/IPFS-and-Blockchain-Principles-and-Practice#1]
chart 4-2
multihash 111469a5a1f4551b82fdc55b9e41e...
you say length  30 byte (Hex code :0x14)

actual  is : 20 byte  because  0x14=20 

you can use ipfs cid format %{b,h,c,P}  bafyreid2yusnaklgts32ysgnxn7hmm5u7m3fqnxxzzh3i5rebwvlbotz7e

**Comment by daijiale** [comment]
> chart 4-2
> multihash 111469a5a1f4551b82fdc55b9e41e...
> you say length 30 byte (Hex code :0x14)
> 
> actual is : 20 byte because 0x14=20
> 
> you can use ipfs cid format %{b,h,c,P} bafyreid2yusnaklgts32ysgnxn7hmm5u7m3fqnxxzzh3i5rebwvlbotz7e

Thanks，roger that
