### ISSUE TITLE
p

### ISSUE THREAD

**Issue by lilianwen** [daijiale/IPFS-and-Blockchain-Principles-and-Practice#12]
p173, 外部资源攻击
恶意节点对网络宣城的数据存储量要比实际存储的少。
这里应该是多，而不是少吧？

**Comment by daijiale** [comment]
外部资源攻击是少的情况，即实际没存这么多，但网络验证时利用外部数据源来充数的场景。

生成攻击是数据存储量要比实际存储的多的情况。
